#!/bin/sh

# This requires that you have luakit installed on NixOS.

luakit_wrapper_1=$(which luakit)
luakit_binary=$(cat "$luakit_wrapper_1" | grep '^exec ' | grep -o -P '/nix/store/[^"]+' | head -n 1)
luakit_rpath=$(patchelf --print-rpath "$luakit_binary")
luakit_interpreter=$(patchelf --print-interpreter "$luakit_binary")

set -eu -o pipefail

for i in ~/.cache/ms-playwright/webkit-*/pw_run.sh; do
	# Fix shebang line
    sed -i -r 's,#!/bin/bash,#!/bin/sh,g' "$i"
done

# Not all .so files here are executable
find ~/.cache/ms-playwright/webkit-*/minibrowser-gtk/ -type f | while read i; do
	echo "$i"
    if ! [[ "$i" == *.so || "$i" == *.so.* ]]; then
	    patchelf --set-interpreter "$luakit_interpreter" "$i" || true
    fi
	patchelf --set-rpath "$luakit_rpath" "$i" || true
done
