#!/usr/bin/env bash

# This program fixes the rpaths and interpreters in the playwright-downloaded browser binaries.
# This requires that you have google-chrome-unstable and firefox-bin installed on NixOS.

set -eu -o pipefail

here=$(dirname "$0")

$here/fix-playwright-chromium
$here/fix-playwright-firefox
$here/fix-playwright-webkit
